partial.tar.xz: partial_20220221-aa partial_20220221-ab
	cat partial_20220221-* > partial.tar.xz

partial: partial.tar.xz
	tar xvf partial.tar.xz

mnaineffects: maineffects.tar.xz
	tar xvf maineffects.tar.xz

